
const SHOP_DATA = [
    {
      id: 1,
      name: "T-shirt with Tape Details",
      category: "NewArrivals",
      image: "/src/assets/T-shirt_with_tape_details.svg",
      new_price: 120,
      old_price: 150,
    },
    {
      id: 30,
      name: "T-shirt with Tape Details",
      category: "NewArrivals",
      image: "/src/assets/T-shirt_with_tape_details.svg",
      new_price: 120,
      old_price: 150,
    },
    {
      id: 2,
      name: "Skinny Fit Jeans",
      category: "NewArrivals",
      image: "/src/assets/Skinny_fit_jeans.svg",
      new_price: 240,
      old_price: 250,
    },
    {
      id: 3,
      name: "Checkered Shirt",
      category: "NewArrivals",
      image: "/src/assets/Checkered_shirt.svg",
      new_price: 180,
      old_price: 200,
    },
    {
      id: 4,
      name: "Sleeve Striped T-shirt",
      category: "NewArrivals",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 130,
      old_price: 150,
    },
    {
      id: 5,
      name: "Green Beanie",
      category: "NewArrivals",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 18,
      old_price: 25,
    },
    {
      id: 6,
      name: "Palm Tree Cap",
      category: "NewArrivals",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 14,
      old_price: 17,
    },
    {
      id: 7,
      name: "Red Beanie",
      category: "NewArrivals",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 18,
      old_price: 25,
    },
    {
      id: 8,
      name: "Wolf Cap",
      category: "On_Sale",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 12,
      old_price: 14,
    },
    {
      id: 9,
      name: "Blue Snapback",
      category: "On_Sale",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 12,
      old_price: 16,
    },
    {
      id: 10,
      name: "Black Snapback",
      category: "On_Sale",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 12,
      old_price: 16,
    },
    {
      id: 11,
      name: "Grey Snapback",
      category: "On_Sale",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 12,
      old_price: 16,
    },
    {
      id: 12,
      name: "Red Snapback",
      category: "On_Sale",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 12,
      old_price: 16,
    },
    {
      id: 13,
      name: "Brown Snapback",
      category: "On_Sale",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 12,
      old_price: 16,
    },
    {
      id: 14,
      name: "Blush Snapback",
      category: "On_Sale",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 12,
      old_price: 16,
    },
    {
      id: 15,
      name: "Blsh Snapback",
      category: "On_Sale",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 12,
      old_price: 16,
    },
    {
      id: 16,
      name: "Blus Snapback",
      category: "Brands",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 16,
      old_price: 102,
    },
    {
      id: 17,
      name: "Adidas NMD",
      category: "Brands",
      image: "/src/assets/brand1.webp",
      new_price: 220,
      old_price: 102,
    },
    {
      id: 18,
      name: "Adidas Yeezy",
      category: "Brands",
      image: "/src/assets/brand2.webp",
      new_price: 280,
      old_price: 102,
    },
    {
      id: 19,
      name: "Black Converse",
      category: "Brands",
      image: "/src/assets/brand3.webp",
      new_price: 110,
      old_price: 102,
    },
    {
      id: 20,
      name: "Nike White AirForce",
      category: "Brands",
      image: "/src/assets/brand4.webp",
      new_price: 160,
      old_price: 102,
    },
    {
      id: 21,
      name: "Nike Red High Tops",
      category: "Brands",
      image: "/src/assets/brand5.webp",
      new_price: 160,
      old_price: 102,
    },
    {
      id: 22,
      name: "Nike Brown High Tops",
      category: "Brands",
      image: "/src/assets/brand6.webp",
      new_price: 160,
      old_price: 102,
    },
    {
      id: 23,
      name: "Air Jordan Limited",
      category: "Brands",
      image: "/src/assets/brand7.webp",
      new_price: 190,
      old_price: 102,
    },
    {
      id: 24,
      name: "Timberlands",
      category: "Brands",
      image: "/src/assets/brand8.webp",
      new_price: 200,
      old_price: 102,
    },
    {
      id: 25,
      name: "Black Jean Shearling",
      category: "Brands",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 125,
      old_price: 102,
    },
    {
      id: 26,
      name: "Blue Jean Jacket",
      category: "Brands",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 90,
      old_price: 102,
    },
    {
      id: 27,
      name: "Grey Jean Jacket",
      category: "Brands",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 90,
      old_price: 102,
    },
    {
      id: 28,
      name: "Brown Shearling",
      category: "Brands",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 165,
      old_price: 102,
    },
    {
      id: 29,
      name: "Tan Trench",
      category: "Brands",
      image: "/src/assets/Sleeve_striped_T-shirt.svg",
      new_price: 185,
      old_price: 102,
    },
  ];
  
  export default SHOP_DATA;
  